version: "3.8"

volumes:
  postgres-data:

networks:
  api:
  database:
  front-end:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  db:
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    container_name: postgres-sandbox
    restart: always
    build:
      context: ./back-end/northwind_psql_sql_example
      target: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/bitnami/postgresql/data
    networks:
      - database

  api-gateway:
    environment:
      - AUTH0_URL=${AUTH0_URL}
      - AUTH0_AUTHZ_URL=${AUTH0_AUTHZ_URL}
      - AUTH0_AUDIENCE_URL=${AUTH0_AUDIENCE_URL}
      - AUTH0_SIGNING_ALG=${AUTH0_SIGNING_ALG}
      - REDIS_PUBLIC_URL=${REDIS_PUBLIC_URL}
      - REST_API_URL=${REST_API_URL}
    container_name: api-gateway-sandbox
    depends_on:
      - redis
      - rest-api
    build:
      context: ./back-end/api-gateway-example
      target: api-gateway
    ports:
      - "3000:3000"
    networks:
      front-end:
        ipv4_address: 172.20.0.3
      api:

  redis:
    container_name: redis-db
    restart: always
    build:
      context: ./back-end/redis-example
      target: redis-container
    ports:
      - "6379:6379"
    networks:
      - api

  rest-api:
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - DATABASE_URL=${DATABASE_URL}
      - AUTH0_URL=${AUTH0_URL}
      - AUTH0_AUDIENCE_URL=${AUTH0_AUDIENCE_URL}
      - AUTH0_SIGNING_ALG=${AUTH0_SIGNING_ALG}
    container_name: rest-api-sandbox
    depends_on:
      - db
    build:
      context: ./back-end/microservice-orm-example
      target: rest-api
    ports:
      - "3001:3001"
    networks:
      - database
      - api

  react:
    environment:
      - VITE_AUTH0_URL=${AUTH0_URL}
      - VITE_AUTH0_AUTHZ_URL=${AUTH0_AUTHZ_URL}
      - VITE_AUTH0_AUDIENCE_URL=${AUTH0_AUDIENCE_URL}
      - VITE_AUTH0_CLIENT_ID={AUTH0_CLIENT_ID}
      - VITE_AUTH0_CLIENT_SECRET={AUTH0_CLIENT_SECRET}
      - VITE_AUTH0_SIGNING_ALG=${AUTH0_SIGNING_ALG}
      - VITE_AUTH0_CALLBACK_URL={AUTH0_CALLBACK_URL}
    container_name: react-sandbox
    depends_on:
      - api-gateway
    build:
      context: ./front-end/react-vite
      target: react-prod
    ports:
      - "4000:4000"
    networks:
      front-end:
        ipv4_address: 172.20.0.2

  storybook:
    container_name: storybook-sandbox
    build:
      context: ./front-end/react-vite
      target: storybook
    ports:
      - "3999:3999"
    networks:
      front-end:
        ipv4_address: 172.20.0.4
